//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_Cuối_Kỳ___Lập_Trình_Hướng_Đối_Tượng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int id { get; set; }
        public int idBill { get; set; }
        public int idMonAn { get; set; }
        public int soluong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual PhieuTamTinhHoaDon PhieuTamTinhHoaDon { get; set; }
    }
}
